const lennys = [
    'https://sm.ign.com/ign_br/screenshot/default/kimetsu-no-yaiba_jc8q.jpg',
    'https://img.ibxk.com.br/2021/05/19/19091406831031.jpg',
    'https://p2.trrsf.com/image/fget/cf/600/400/images.terra.com/2021/09/10/demon-slayer-nezuko.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNm8ruVpTKVmmOaq0YToVDaYk3GVHE5kMjHGv7xUvlA4NSGRbKhq0j8LmStjUYUk_OMDk&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVb85Hw7-4C4ErrFmtKarUFJpeX3dULyu-r20AgYoGNTRu-a4wq4DDeMxXJ7lsSYbDOls&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtv6h3fQnZ9xHLZKaPJo5xnhi1zNKO0JxAmCQoDYJ0pletB5vPZIrl3FK8rrV6DduUqVs&usqp=CAU',
    'https://www.comboinfinito.com.br/principal/wp-content/uploads/2020/02/demon-slayer-manga-190-ler-online.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaPaGB1sskoUToFkubx0YlU7HjUY8N9iGgBQ&usqp=CAU',
    'https://s.aficionados.com.br/imagens/kanao-tsuyuri-1_cke.jpg',
    'https://criticalhits.com.br/wp-content/uploads/2020/09/Screenshot_13-1.jpg',
    'https://1.bp.blogspot.com/-YgMorN261sc/XaENXcNETFI/AAAAAAAAx3U/h8AGcCOoJh8k7N-5KKf-LgBr2rlLw3S2gCLcBGAsYHQ/s1600/Giyuu%2BTomioka%2BPersonagens%2Bde%2BDemon%2BSlayer.jpg',
    'https://tm.ibxk.com.br/2021/06/04/04133604163033.jpg',
    'https://www.omegascopio.com.br/wp-content/uploads/2021/04/sabito_makomo_demon_slayer_nendoroid.jpg_423682103.jpg',
    "https://s.aficionados.com.br/imagens/demon-slayer-kimetsu-no-yaiba-os-personagens-principais-sua-historia-e-poderes_f.jpg",
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTaSy2riK1CYSyTB3lAJZHEhEEco8OeF8P0Q&usqp=CAU',
    "https://images2.alphacoders.com/100/thumb-1920-1007550.jpg",
    'https://wallpaperaccess.com/full/1099445.png',
    'https://www.nawpic.com/media/2020/demon-slayer-desktop-nawpic.jpg',
    'https://wallpaperforu.com/wp-content/uploads/2021/05/Wallpaper-Anime-Demon-Slayer-Kimetsu-No-Yaiba-Giyuu-Tom13-scaled.jpg',
    'https://wallsexpert.com/wp-content/uploads/2021/08/Demon-Slayer-Laptop-Wallpaper.jpeg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWZzx1kTAwlRqoFV0folv_rcgLarWz4M7oxw&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHHdv-WI5TLe_7H0wBNhofO3aWepRFm4MnVA&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToNk-MERpPu7Kkx8WZsg_m5ohwMLL9bOuFVQ&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuDGEFm7jXUE2h5igWjT9fB87_DInbELRS2d_Nn8cDt6CtzGIUJNoEmEQsxOMGogJLGAM&usqp=CAU',
    'https://c4.wallpaperflare.com/wallpaper/368/380/864/anime-demon-slayer-kimetsu-no-yaiba-boy-girl-nezuko-kamado-hd-wallpaper-preview.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSko4LHPSjzNp1VRd4OoK_4zSjIeniEOuQNAzyBmg-JZth-pCwWrMAM0qFxDy2KYMjbXk4&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQclnx5mx3_SaIY0DKkAYDz7iN9KK-cStlzO9CPYHjX7EhFX67GC5qKihZz3nqjz_pbRTk&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU7bHKNgYju3FTrWLSGwHiFUegdDa-I1vALmg0mb9McJKzp-CHDaeINMgTu3q4dnkOIYU&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL8TBthl4Sidp-3zqOT5EztxR5mnSr-Z5MVw&usqp=CAU',
    'https://p4.wallpaperbetter.com/wallpaper/116/560/907/anime-demon-slayer-kimetsu-no-yaiba-shinobu-kochou-hd-wallpaper-preview.jpg',
    'https://c.wallhere.com/photos/28/a2/Kimetsu_no_Yaiba_Kochou_Shinobu_butterfly_weapon_katana_black_hair_uniform_Japanese_clothes-1672881.jpg!d',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGfacvH5SYkNbmp8J17BcqJ4zeVcatZAGrc1hinhWVk8Prl7p-r9snuGZseihU-QIl060&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHA6I2umq_suCe24Y1F0iOKf7FPjhipdGpQfrMxBM7YqmMYuo4BHvsOfp34FWYlYDnSXg&usqp=CAU',
    'https://play-lh.googleusercontent.com/g_k0sryhnNXFZr6AZaw391dZFtTeUN0HivPm8iuDdG7QaWgHgE6Tl07oFRj8FxOWBRQ=h1024-no-tmp_kimetsu_no_yaiba_wallpaper_hd_apk.jpg',
    'https://images2.alphacoders.com/100/thumb-1920-1007550.jpg',
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrmifUaHvzP9qmgpri2r9j4DCAV2TuIkLPKA&usqp=CAU",
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUK2R6PAMvzFvAJ21EbEi6wN3_ViMToW7R_e0x-BPVjwqtyA86VTczZeCIxZCyg4QFaKY&usqp=CAU',
    'https://i.ytimg.com/vi/fc2s1a7ZdkY/maxresdefault.jpg',
    'https://c4.wallpaperflare.com/wallpaper/234/94/564/anime-demon-slayer-kimetsu-no-yaiba-tanjirou-kamado-hd-wallpaper-thumb.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqVyKZMGfM8NDqpjfycEfqYkLm3ilU6MlRzg&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgruN69ZHJz_V7oeAhA14bqYaGrTx8Ho--ag&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-p4jtrP1hrm8VVS8rvy7QPz6xnun9ALog_Q&usqp=CAU',
    "https://i.pinimg.com/originals/97/44/1f/97441f7dbd5c330bee0306c0008a77d0.jpg",
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQvtRHVIN_60oqEW-KZDSD0WyQOBhVdNUxkA&usqp=CAU',
    'https://1.bp.blogspot.com/-f6av8dcSfaA/XyVQZcocM5I/AAAAAAAADnI/2_Pow9-qdV8FdatTny7rhtHSUKy7M3YvACLcBGAsYHQ/d/Demon%2BSlayer%2B-%2BKimetsu%2BNo%2BYaiba%2BAnime%2BWallpaper%2B1920x1080_01.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaozwcYYAUr10iPSEAb-SOrIRAZLpmGPD2icOQxOAptGfe585-Fy__uleYro22eAJFpzA&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWB4AkAmJZPJmK5W7f39Dvl1fnsifSOTAy3xcKGjV4Z0M9wCyGp_4DqqE0a_n6esIC2ak&usqp=CAU',
    'https://wallpaperaccess.com/full/2661458.jpg',
    "https://lh3.googleusercontent.com/proxy/PApSihsz81-zDuPR2kWkKgO9rCXfjso7LKI6IJluOnb2llhrkTExSgShgsUeYs-UKLWqlRndMD5soJFE67NmulgxsyOQdjhL6J75F9LuRLcsdYENGCm-eIzAUzdU3c11y6hDXq53m35ZC5CH-w",
    'http://dslv9ilpbe7p1.cloudfront.net/Aki6rr3kEmVHaki8HSCnLA_store_banner_image.png',
    'https://kanto.legiaodosherois.com.br/w760-h398-gnw-cfill-q80/wp-content/uploads/2021/11/legiao_KsjMrgiuHW80.png.jpeg',
    'https://akcdn.detik.net.id/visual/2020/11/16/demon-slayer-mugen-train_169.png?w=650',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtid_avJH--7D6wzIpIuxWa-dqaiyXaPAMzg&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZs3eJ9ky5AxV2UsSdVRpFGm1uo1s-2EucNSZp8gaa731s1GKiEK1Mf57KrrVwfxpGHHM&usqp=CAU',
    'https://c4.wallpaperflare.com/wallpaper/368/380/864/anime-demon-slayer-kimetsu-no-yaiba-boy-girl-nezuko-kamado-hd-wallpaper-preview.jpg',
    'https://img.olhardigital.com.br/wp-content/uploads/2021/02/demon-slayer-1024x410.jpg',
    'https://wallpapermoon.com/wp-content/uploads/2021/11/00030097.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKoT5DsFsnV0MBNSR8h1ANUQlGwGrnuIIYg4_i2HwRstmWuafHrE6mWmD2Z5GGeq1TjpI&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiObLlpdamEC7paXruufce6J8B7YLOU3Epf_rGT2i1h9Rzgf0kGRc2PTt1uhuBpJMAX1Q&usqp=CAU',
    'https://images4.alphacoders.com/102/thumb-350-1028306.png',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQROa_4sulNgAmALvgnAw8Ochyv2JnOXoHXHg&usqp=CAU',
    'https://images.hdqwalls.com/download/demon-slayer-samurai-anime-girl-4k-kd-1280x1024.jpg',
    'https://freeaddon.com/wp-content/uploads/2021/06/Them-chu-HD-vao-anh-2.png',
    'https://play-lh.googleusercontent.com/g_k0sryhnNXFZr6AZaw391dZFtTeUN0HivPm8iuDdG7QaWgHgE6Tl07oFRj8FxOWBRQ=h1024-no-tmp_kimetsu_no_yaiba_wallpaper_hd_apk.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4dsGSf_RDI4myUiOvhk0VLxOdgXMxbV-45Q&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGdNYh6GalA8CqUfe7OjGmf-PM-Gg9N-z_cg&usqp=CAU',
    'https://www.enjpg.com/img/2020/demon-slayer-desktop-3.jpg',
    'https://c4.wallpaperflare.com/wallpaper/508/596/918/anime-demon-slayer-kimetsu-no-yaiba-shinobu-kochou-hd-wallpaper-preview.jpg',
    'https://desktopwallpapershd.com/wp-content/uploads/2021/04/Demon-Slayer-Wallpaper.jpg',
    'https://files.livewallp.com/wp-content/uploads/2021/08/Demon-Slayer-Tomioka-Yoshiyuki-Live-Wallpaper-Preview-Breath-of-the-Sea.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX2Sh5-aFfCruSHzx8hfGeqf2fZtL7xcGxSg_NC-1lBd4VI33Y125p4EgJBQRG2mfa8qM&usqp=CAU',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7wJMR3P-7FzBCuRaiDnHhxNilw8mGkoPTFXvP5R7R0oLrDLXl2s5pGjIpMqD8c1aRTbI&usqp=CAU'
  ]


module.exports.run = async (bot, message, args) => {
    var rand_num = Math.floor(Math.random() * lennys.length);
    var rand_val = lennys[rand_num];

    return message.channel.send(rand_val);
}

module.exports.help = {
    name: "aquelacarinha",
    aliases: ["lenny"],
    descr: 'Lenny face.'
} 